import NavBar from './components/nav-bar'
import * as styles from './layout.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.rootCss}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
